services:
    app_bundle.form.image_message_type:
        class: AppBundle\Form\ImageMessageType
        calls:
            - ["setParameters",["%image_upload%"]]
        tags:
            - { name: form.type }
    app_bundle.image_uploader:
        class: AppBundle\Services\FileUploader
        arguments: ['%image_upload%']

    app_bundle.counter_pages:
        class: AppBundle\Services\VisitsCounter
        arguments: ['@doctrine.orm.entity_manager']

    app_bundle.export_excel:
        class: AppBundle\Services\ExcelExport
        arguments: ['@phpexcel']
